### ISSUE TITLE
Tokio latest version possibility.

### ISSUE THREAD

**Issue by gustav3d** [tormol/uds#6]
Hello,

Is it possible to update tokio dependency, so your able to use the latest version in a project, and not having and old outdated version also pulled - in only for uds ?.

**Comment by tormol** [comment]
Yeah, I don't use tokio myself but saw 0.2 is really old at this point.
Supporting more than one tokio version seems hard so I'll get the already merged features released and then update tokio and release that.
Or you can open a PR that updates it. ;)

**Comment by cgwalters** [comment]
Alternatively, perhaps this code should go into tokio core?
